### ISSUE TITLE
Possible to Break Original layout

### ISSUE THREAD

**Issue by nindim** [brunomikoski/Animation-Sequencer#15]
Hi,

I have noticed that if I configure the AnimationSequencer in certain ways I can break the original Editor UI layout.

For the record, I don't expect the setups below to yield correct animation results during Preview/Runtime, they are definitely misconfigured. I just don't expect my original layout to be broken post-preview as a result of my mistake.

Example 1 - "Move to Anchored Position" in From Direction and a "Shake Position".
![image](https://user-images.githubusercontent.com/7597004/127736923-65e113c2-5560-4092-b128-8ca46ebcceb4.png)
![image](https://user-images.githubusercontent.com/7597004/127736930-861744a7-f43c-40ff-8d05-527896369e55.png)

Result: With this particular combination the position of the Tween Target is left at the start of the "Move to Anchored Position".
![image](https://user-images.githubusercontent.com/7597004/127736942-a18b816c-2ca8-49ab-86c0-afdc21210a49.png)

Example 2 - "Rotate to Euler Angles" and "Shake Rotation"
![image](https://user-images.githubusercontent.com/7597004/127736834-2d1e8928-b022-4bb0-83a2-b8e776e1e105.png)
![image](https://user-images.githubusercontent.com/7597004/127736840-7ce2a6a7-080f-43f2-9d64-148c46678ca5.png)

Result: A seemingly random rotation is left on the RectTransform.
![image](https://user-images.githubusercontent.com/7597004/127736851-a233c52c-59dc-45d8-accd-1c803d793bee.png)

Both issues occur when they are combined as Actions within a single step or as separate Actions that are Joined.

I doubt this is limited to just the actions I have listed above, I expect driving any variable with more than s single step/action at once will cause issues.

Thanks a lot,

Niall

**Comment by brunomikoski** [comment]
I will investigate it properly, can you confirm what version of the DOTween you are using it? 

There was a version some time ago that caused similar issues to the ones you mentioned.

**Comment by brunomikoski** [comment]
I believe most of the issues that could cause this has been fixed on v0.2.0!

**Comment by nindim** [comment]
Hey @brunomikoski!

I am using DOTween 1.2.420:
![image](https://user-images.githubusercontent.com/7597004/131488602-84834ba6-5e7a-48a1-8e7a-ea886c9d256c.png)

I will try version 0.2.0 and report back :)

**Comment by nindim** [comment]
Hey @brunomikoski,

I am still seeing these issues in the latest version of Animation-Sequencer 0.2.4 and DOTween 1.2.632.

I have attached a  reproduction project showing the first use case in the original bug report.

Repro Steps:

1. Open SampleScene
2. Note the location of the white square
2. Select Image
3. Notice "Image" position is (128, 0, 0)
2. Select Canvas
3. Press Play
4. Wait for the preview to end
5. Press Stop
6. Notice the white square is not where it started.
5. Select Image
4. Notice "Image" position is (-510, 0 0) rather than (128, 0, 0)

[AnimationSequencerTest_0.2.4.zip](https://github.com/brunomikoski/Animation-Sequencer/files/7315479/AnimationSequencerTest_0.2.4.zip)

Thanks a  lot,

Niall
